# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = {
  'kaa-cl' => '10',
  'kaa-lb1' => '21',
  'kaa-lb2' => '22',
  'kaa-srv1' => '31',
  'kaa-srv2' => '32',
}

Vagrant.configure("2") do |config|
  config.vm.network "private_network", virtualbox__intnet: true, auto_config: false
  config.vm.box = "bento/ubuntu-20.04"

  boxes.each do |k, v|
    config.vm.define k do |node|
      node.vm.provision "shell" do |s|
        s.inline = "hostname $1;"\
        "ip addr add $2 dev eth1;"\
        "ip link set dev eth1 up;"\
        "apt update;"
        s.args = [k, "172.28.128.#{v}/24"]
      end
    end
  end
    # client
    config.vm.define "kaa-cl" do |cl|
        cl.vm.provision "shell" do |s|
        s.inline = "apt -y install arping;"\
        "apt -y install iperf3;"\
        "apt -y install iftop;"
        end
    end
    # Load balancer 1
    config.vm.define "kaa-lb1" do |lb1|
        lb1.vm.provision "shell" do |s|
        s.inline = "apt -y install ipvsadm;"\
        "ipvsadm -A -t 172.28.128.200:80 -s rr;"\
        "ipvsadm -a -t 172.28.128.200:80 -r 172.28.128.31:80 -g -w 1;"\
        "ipvsadm -a -t 172.28.128.200:80 -r 172.28.128.32:80 -g -w 1;"\
        "apt -y install keepalived;"\
#        config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
#        "cp /vagrant/keepalived.conf.main /etc/keepalived/keepalived.conf;"\ Не копирует !!
#        "chmod 644 /etc/keepalived/keepalived.conf;"\
        "systemctl enable keepalived;"\
        "systemctl start keepalived;"
        end
    end
    # Load balancer 2
    config.vm.define "kaa-lb2" do |lb2|
        lb2.vm.provision "shell" do |s|
        s.inline = "apt -y install ipvsadm;"\
        "ipvsadm -A -t 172.28.128.200:80 -s rr;"\
        "ipvsadm -a -t 172.28.128.200:80 -r 172.28.128.31:80 -g -w 1;"\
        "ipvsadm -a -t 172.28.128.200:80 -r 172.28.128.32:80 -g -w 1;"\
        "apt -y install keepalived;"\
#        config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
#        "cp /vagrant/keepalived.conf.backup /etc/keepalived/keepalived.conf;"\
#        "chmod 644 /etc/keepalived/keepalived.conf;"\
        "systemctl enable keepalived;"\
        "systemctl start keepalived;"
        end
    end

    # "Real" Server 1
    config.vm.define "kaa-srv1" do |srv1|
        srv1.vm.provision "shell" do |s|
        s.inline = "apt -y install nginx;"\
        "sysctl -w net.ipv4.conf.all.arp_ignore=1;"\
        "sysctl -w net.ipv4.conf.all.arp_announce=2;"\
        "ip addr add 172.28.128.200/32 dev lo label lo:200;"
        end
    end
    # "Real" Server 2
    config.vm.define "kaa-srv2" do |srv2|
        srv2.vm.provision "shell" do |s|
        s.inline = "apt -y install nginx;"\
        "sysctl -w net.ipv4.conf.all.arp_ignore=1;"\
        "sysctl -w net.ipv4.conf.all.arp_announce=2;"\
        "ip addr add 172.28.128.200/32 dev lo label lo:200;"
        end
    end
end
